services:
  # MySQL for Order Service
  order-mysql:
    image: mysql:8.0
    container_name: order-service-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order-service
    ports:
      - "3306:3306"
    volumes:
      - order-mysql-data:/var/lib/mysql
    networks:
      - microservices-network

  # MongoDB for Product Service
  product-mongodb:
    image: mongo:7.0
    container_name: product-service-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: product-service
    ports:
      - "27017:27017"
    volumes:
      - product-mongodb-data:/data/db
    networks:
      - microservices-network

volumes:
  order-mysql-data:
  product-mongodb-data:

networks:
  microservices-network:
    driver: bridge